### ISSUE TITLE
Variable "gos_web_socket_server_host" does not exist.

### ISSUE THREAD

**Issue by Lyro1** [GeniusesOfSymfony/WebsocketAppDemo#15]
I just did the following:

1. Clone the repository
2. `cd WebSocketAppDemo`
3. `composer install`
4. `symfony server:start`, it's running on port 8000
5. Open a new tab of my terminal
6. `php bin/console gos:websocket:server`
7. Open Safari, go to `https://127.0.0.1:8000`

I get the following error: 

<img width="1440" alt="Capture d’écran 2020-11-18 à 15 37 06" src="https://user-images.githubusercontent.com/22308289/99543843-eb63c080-29b3-11eb-8dfa-09178517bb33.png">

It seems the variables required in the homepage template (line 12) are not set in Symfony. Did I do something wrong?

**Comment by mbabker** [comment]
I don't use the `symfony` binary, but after cloning the repo fresh on my newer computer I hit the same problem then after updating everything in the app to latest stable versions it's all working again.

(I really should make a "better" demo one day though)
