### ISSUE TITLE
cboden/ratchet vs gos/ratchet

### ISSUE THREAD

**Issue by skler** [GeniusesOfSymfony/WebsocketAppDemo#2]
Hi, 

I'm unable to run the demo because this error: 

```
[Symfony\Component\Debug\Exception\ContextErrorException]
  Catchable Fatal Error: Argument 1 passed to Ratchet\Wamp\TopicManager::__construct() must implement interface Ratchet\Wamp\WampServerInterface, none given, called in /WebsocketAppDemo/app/cache/dev/appDevDebugProjectContainer.php on line 2060 and defined
```

This I guess is because both ```cboden/ratchet``` and ```gos/ratchet``` libs are required as deps. The code seems wrote for ```gos/ratchet``` but the problem is that the two libs have the same namespace with different constructors.

Can you fix it?

**Comment by ProPheT777** [comment]
oh yes sorry I didn't upgrade since this commit :(

Yes I have create a gos/ratchet repo in order to unlock fast feature without waiting official ratchet release. So I kept the same namespace because it's intended to replace ratchet at all.

**Comment by skler** [comment]
but can be fixed?

**Comment by ProPheT777** [comment]
no, because if I fixed it, I break all application which is using WebsocketBundle

**Comment by pe77** [comment]
JESUS!

pls bro. I can't use the demo

**Comment by ProPheT777** [comment]
Yeah bro, I know it's anoying. 

So it's resolved !!!!!! :tada: 

@skler I finally find a way via composer replace feature :)

**Comment by SakyaStelios** [comment]
I have the error too. It is not fixed :/

**Comment by ProPheT777** [comment]
Are you sure to have the latest version ? 

[![asciicast](https://asciinema.org/a/27468.png)](https://asciinema.org/a/27468)

**Comment by pe77** [comment]
My problem was a version. I update(btw, delete/install again), then work! Try this. =D
