### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by garak** [GeniusesOfSymfony/WebsocketAppDemo#3]
Fatal error: Class 'Symfony\Component\Debug\Debug' not found in /WebsocketAppDemo/web/app_dev.php on line 21

Tried to install manually `symfony/debug`, no luck

**Comment by cedricJack** [comment]
Yep I confirm this garak's comment.  This demo not working !

**Comment by ProPheT777** [comment]
Should be fixed now :) awaiting your feedback

**Comment by cedricJack** [comment]
@ProPheT777  fail 
![capture d ecran de 2016-03-17 13 37 22](https://cloud.githubusercontent.com/assets/2599335/13846164/6e152138-ec45-11e5-9aec-235a31977946.png)

**Comment by garak** [comment]
I'm getting the same error (about missing Debug)

**Comment by ProPheT777** [comment]
Ok, duno why but app_dev.php was fucked. Anyway now it's fixed. Sorry :(

**Comment by garak** [comment]
Unable to find file "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml" in @SensioDistributionBundle/Resources/config/routing/webconfigurator.xml (which is being imported from "/WebsocketAppDemo/app/config/routing_dev.yml"). Make sure the "SensioDistributionBundle" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, make sure the bundle path "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml" is not empty.

**Comment by cedricJack** [comment]
@ProPheT777   
![capture d ecran de 2016-03-17 15 29 32](https://cloud.githubusercontent.com/assets/2599335/13849125/1249e752-ec55-11e5-8323-67855f44840b.png)

**Comment by cedricJack** [comment]
please comment in routing_dev.yml 

#_configurator:
#    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
#    prefix:   /_configurator

**Comment by cedricJack** [comment]
![capture d ecran de 2016-03-17 16 20 25](https://cloud.githubusercontent.com/assets/2599335/13850878/2cee6d24-ec5c-11e5-983a-87640a386894.png)
